services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: labdb
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    environment:
      DATABASE_URL: postgresql://labuser:labpassword@db:5432/labdb
    ports:
      - "5050:5000"
    depends_on:
      - db

volumes:
  postgres_data:
